//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "categories_category")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name_uz: String,
    pub name_ru: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::private_workers_privateworker_categories::Entity")]
    PrivateWorkersPrivateworkerCategories,
    #[sea_orm(has_many = "super::services_service_categories::Entity")]
    ServicesServiceCategories,
}

impl Related<super::private_workers_privateworker_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PrivateWorkersPrivateworkerCategories.def()
    }
}

impl Related<super::services_service_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServicesServiceCategories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
