//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "django_session")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub session_key: String,
    #[sea_orm(column_type = "Text")]
    pub session_data: String,
    pub expire_date: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
