//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub mod prelude;

pub mod auth_group;
pub mod auth_group_permissions;
pub mod auth_permission;
pub mod auth_user;
pub mod auth_user_groups;
pub mod auth_user_user_permissions;
pub mod business;
pub mod categories_category;
pub mod django_admin_log;
pub mod django_content_type;
pub mod django_migrations;
pub mod django_session;
pub mod no_code_product;
pub mod parent_no_code_product;
pub mod parent_product;
pub mod parent_weight_item;
pub mod private_workers_privateworker;
pub mod private_workers_privateworker_categories;
pub mod product;
pub mod rent;
pub mod rent_history;
pub mod services_location;
pub mod services_service;
pub mod services_service_categories;
pub mod session;
pub mod telegram_user;
pub mod tgbot_botuser;
pub mod user;
pub mod verification;
pub mod weight_item;
