//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "private_workers_privateworker")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub first_name: String,
    pub last_name: String,
    pub lang: Vec<String>,
    pub image: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub bio_ru: String,
    #[sea_orm(column_type = "Text")]
    pub bio_uz: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::private_workers_privateworker_categories::Entity")]
    PrivateWorkersPrivateworkerCategories,
}

impl Related<super::private_workers_privateworker_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PrivateWorkersPrivateworkerCategories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
