//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "private_workers_privateworker_categories")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub privateworker_id: i64,
    pub category_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::categories_category::Entity",
        from = "Column::CategoryId",
        to = "super::categories_category::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CategoriesCategory,
    #[sea_orm(
        belongs_to = "super::private_workers_privateworker::Entity",
        from = "Column::PrivateworkerId",
        to = "super::private_workers_privateworker::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PrivateWorkersPrivateworker,
}

impl Related<super::categories_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CategoriesCategory.def()
    }
}

impl Related<super::private_workers_privateworker::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PrivateWorkersPrivateworker.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
