//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub price: i64,
    pub business_id: i64,
    pub parent_product_id: i64,
    pub expiration_date: Date,
    pub quantity: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::business::Entity",
        from = "Column::BusinessId",
        to = "super::business::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Business,
    #[sea_orm(
        belongs_to = "super::parent_product::Entity",
        from = "Column::ParentProductId",
        to = "super::parent_product::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ParentProduct,
}

impl Related<super::business::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Business.def()
    }
}

impl Related<super::parent_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ParentProduct.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
