//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "services_service")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description_ru: String,
    #[sea_orm(column_type = "Text")]
    pub description_uz: String,
    pub image: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::services_location::Entity")]
    ServicesLocation,
    #[sea_orm(has_many = "super::services_service_categories::Entity")]
    ServicesServiceCategories,
}

impl Related<super::services_location::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServicesLocation.def()
    }
}

impl Related<super::services_service_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServicesServiceCategories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
